name: main
on:
  push:
    branches:
      - main
jobs:
  main-e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Set up Node.js 🚀
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          # if there is no gold image to compare a screenshot to
          # it is a problem, and we should fail the tests
          env: failOnMissingGoldImage=true

      # after the test run completes store the screenshots and diffs
      - name: Save screenshots 📸
        uses: actions/upload-artifact@v4
        # always upload the screenshots, even if the tests fail
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
